amcl:
  ros__parameters:
    use_sim_time: true
    odom_frame_id: odom
    base_frame_id: base_link
    scan_topic: /scan
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.2
    kld_err: 0.01
    kld_z: 0.99
    laser_model_type: "likelihood_field"
    max_beams: 60
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    z_hit: 0.8
    z_rand: 0.1
    laser_likelihood_max_dist: 2.0


