local_costmap:
  ros__parameters:
    update_frequency: 10.0
    publish_frequency: 10.0
    global_frame: odom
    robot_base_frame: base_footprint
    use_sim_time: True
    rolling_window: True
    width: 3
    height: 3
    resolution: 0.05
    robot_radius: 0.22
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
